version: '3'


x-default-opts: 
  &default-opts
  image: hadoop-hbase-spark
  logging:
    options:
      max-size: "1m" 
  networks:
    - hadoopnet


services:
  hadoop-master:
    <<: *default-opts
    hostname: hadoop-master
    container_name: hadoop-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  hadoop-slave1:
    <<: *default-opts
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    ports:
      - "8040:8042"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
  hadoop-slave2:
    <<: *default-opts
    hostname: hadoop-slave2
    container_name: hadoop-slave2
    ports:
      - "8041:8042"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

networks:
  hadoopnet:
    driver: bridge